version: "3.8"
services:
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - "28080:8080"
  openresty:
    image: openresty/openresty:1.25.3.1-5-alpine
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./certs:/certs
    ports:
      - "18080:8080"
      - "18443:8443"
  envoy:
    image: envoyproxy/envoy:v1.24.7
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml --service-cluster front-proxy --file-flush-interval-msec 50
    ports:
      - "9000:9000"
      - "8000:8000"
  upstream-service:
    image: renukafernando/request-info:latest
    command: -pretty -logH -logB
    ports:
      - "8080:8080"