version: "3.8"
services:
  nginx:
    image: nginx:1.23.2-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - "8080:8080"
  openresty:
    image: openresty/openresty:1.25.3.1-5-alpine
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./certs:/certs
    ports:
      - "18080:8080"
  upstream-service:
    image: renukafernando/request-info:latest
    command: -pretty -logH -logB
